apps/urls.py
"""定义apps的URL模式"""

from django.conf.urls import url

from . import views
from django.urls import path



urlpatterns = [
    #主页
    path(r'', views.index, name='index'),
    path(r'topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views


urlpatterns = [

    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register')
]

zblsite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.urls', 'apps'), namespace='apps')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

from functools import wraps

apps/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Topic(models.Model):

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):

        return self.text


class Entry(models.Model):

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):

        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

apps/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

apps/views.py
from django.shortcuts import render

# Create your views here.
from .models import Topic, Entry
from django.contrib.auth.decorators import login_required
from django.http import  HttpResponseRedirect, Http404


def index(request):
    """"""
    return render(request, 'apps/index.html')


@login_required
def topics(request):
    """"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'apps/topics.html', context)


@login_required
def topic(request, topic_id):
    """"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'apps/topic.html', context)


from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TopicForm, EntryForm


@login_required
def new_topic(request):

    if request.method != 'POST':

        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('apps:topics'))

    context = {'form': form}
    return render(request, 'apps/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('apps:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'apps/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('apps:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'apps/edit_entry.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.views import LogoutView
from django.contrib.auth.forms import UserCreationForm


def login_view(request):
    login(request, request.user)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('apps:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('apps:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

apps/templates/apps/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
<p>
    <a href="{% url 'apps:index' %}">Learning Log</a> -
    <a href="{% url 'apps:topics' %}">Topics</a> -
    {% if user.is_authenticated %}
      Hello, {{ user.username }}.
      <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
      <a href="{% url 'users:register' %}">register</a> -
      <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}
</body>
</html>

apps/templates/apps/edit_entry.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{% extends "apps/base.html"%}

{% block content %}

  <p><a href="{% url 'apps:topic' topic.id %}">{{  topic  }}</a></p>

  <p>Edit entry:</p>
  <form action="{% url 'apps:edit_entry' entry.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">save changes</button>
  </form>

{% endblock content %}
</body>
</html>

apps/templates/apps/index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{% extends "apps/base.html"%}

{% block content %}

<p>apps helps you keep track of your learning, for any topic you're
learning about.</p>
{% endblock content %}
</body>
</html>

apps/templates/apps/new_entry.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{% extends "apps/base.html"%}

{% block content %}

  <p><a href="{% url 'apps:topic' topic.id %}">{{  topic  }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'apps:new_entry' topic.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">add topic</button>
  </form>

{% endblock content %}
</body>
</html>

apps/templates/apps/new_topic.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{% extends "apps/base.html"%}

{% block content %}

  <p>Add a new topic:</p>
  <form action="{% url 'apps:new_topic' %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">add topic</button>
  </form>

{% endblock content %}
</body>
</html>

apps/templates/apps/topic.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{% extends "apps/base.html"%}

{% block content %}

  <p>Topic: {{ topic }}</p>

  <p>Entiries:</p>
  <p>
      <a href="{% url 'apps:new_entry' topic.id %}">add new entry</a>
  </p>
  <ul>
      {% for entry in entries %}
      <li>
          <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
          <p>{{ entry.text|linebreaks }}</p>
          <p><a href="{% url 'apps:edit_entry' entry.id %}">edit entry</a></p>
      </li>
      {% empty %}
      <li>
          There are no entries for this topic yet.
      </li>
      {% endfor %}
  </ul>

{% endblock content %}
</body>
</html>

apps/templates/apps/topics.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{% extends "apps/base.html"%}

{% block content %}

  <p>Topics</p>

  <ul>
      {% for topic in topics %}
      <li>
          <a href="{% url 'apps:topic' topic.id %}">{{ topic }}</a>
      </li>
      {% empty %}
      <li> No topics have been added yet.</li>
      {% endfor %}
  </ul>
  <a href="{% url 'apps:new_topic' %}">Add a new topic:</a>

{% endblock content %}
</body>
</html>

users/templates/users/login.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{% extends "apps/base.html"%}

{% block content %}

  {% if form.errors %}
  <p>Your username and password didn't match. Please try again</p>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}">
      {% csrf_token %}
      {{ form.as_p }}

      <button name="submit">log in</button>
      <input type="hidden" name="next" value="{% url 'apps:index' %}" />
  </form>
{% endblock content %}
</body>
</html>

users/templates/users/register.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{% extends "apps/base.html"%}

{% block content %}

 <form method="post" action="{% url 'users:register' %}" >
     {% csrf_token %}
     {{ form.as_p }}

     <button name="submit">register</button>
     <input type="hidden" name="next" value="{% url 'apps:index' %}" />
 </form>
{% endblock content %}
</body>
</html>